import type { ProfileHeroMotion, ProfileVisitEntranceAnim } from './profilePremiumExtras';

export const HERO_MOTION_LABELS: Record<ProfileHeroMotion, string> = {
  none: 'Brak',
  'apex-grid': 'Glass Drift',
  ignition: 'Afterglow',
  'neon-rain': 'Satin',
  'turbo-pulse': 'Orbit',
  shimmer: 'Polysk',
  float: 'Unos',
  pulse: 'Puls',
  aurora: 'Aurora Mist',
  embers: 'Pył',
  kenburns: 'Slow Cinema',
  glitch: 'Film Scan',
  vortex: 'Contour',
  prism: 'Pryzmat',
  matrix: 'Matrix',
  storm: 'Burza',
  hologram: 'Hologram',
  'neon-grid': 'Neon siatka',
};

export const VISIT_ENTRANCE_LABELS: Record<ProfileVisitEntranceAnim, string> = {
  none: 'Brak',
  'apex-reveal': 'Velvet',
  'garage-ignition': 'Horizon',
  'neon-impact': 'Halo',
  'hyper-tunnel': 'Depth',
  sparkle: 'Iskry',
  'hero-flash': 'Flash',
  rings: 'Ringi',
  glow: 'Glow',
  sweep: 'Sweep',
  shockwave: 'Shockwave',
  confetti: 'Konfetti',
  lightning: 'Trace',
  curtain: 'Kurtyna',
  portal: 'Aperture',
  meteor: 'Meteor',
  iris: 'Focus',
  turbo: 'Velocity',
  signal: 'Signal',
  chromaburst: 'Prism Veil',
};
