import { COMMUNITY_ACCENTS } from '../community/communityTheme';
import type { EntranceFxPreset, EntranceFxPresetId } from './entranceFxTypes';

const CYAN = '#10f5ff';
const WHITE = '#ffffff';

export const ENTRANCE_FX_PRESETS: Record<EntranceFxPresetId, EntranceFxPreset> = {
  'arena-duel': {
    id: 'arena-duel',
    durationMs: 2850,
    eyebrow: 'VROOM ARENA',
    title: 'POJEDYNEK DNIA',
    subtitle: 'ODPAL ARENE I WYBIERZ ZWYCIĘZCĘ',
    bgGradient: ['#1f0505', '#030303', '#0d0700'],
    gateLeftGradient: ['#250606', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#070707', '#2c2300'],
    accents: { primary: COMMUNITY_ACCENTS.duelAlt, secondary: COMMUNITY_ACCENTS.duel, cyan: CYAN },
    showVsRow: true,
    showGates: true,
    showClash: true,
    showOncePolicy: 'day',
  },
  'arena-grid': {
    id: 'arena-grid',
    durationMs: 2600,
    eyebrow: 'VROOM ARENA',
    title: 'THE GRID',
    subtitle: 'WALCZ O LEGENDARY — WYBIERZ ZWYCIĘZCĘ',
    bgGradient: ['#1a1200', '#030303', '#0a0800'],
    gateLeftGradient: ['#1a1500', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#070707', '#2c2300'],
    accents: { primary: COMMUNITY_ACCENTS.grid, secondary: COMMUNITY_ACCENTS.duelAlt, cyan: CYAN },
    showVsRow: true,
    showGates: true,
    showClash: true,
    showOncePolicy: 'session',
    iconLeft: 'flag-checkered',
    iconRight: 'flag-checkered',
  },
  'live-chat': {
    id: 'live-chat',
    durationMs: 1200,
    eyebrow: 'SPOŁECZNOŚĆ',
    title: 'CZAT OGÓLNY',
    subtitle: 'LIVE · CAŁA SPOŁECZNOŚĆ VROOM',
    bgGradient: ['#051205', '#030303', '#050a05'],
    gateLeftGradient: ['#0a1a0a', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#0a1a0a'],
    accents: { primary: COMMUNITY_ACCENTS.public, secondary: '#2a8a20', cyan: CYAN },
    showVsRow: false,
    showGates: true,
    showClash: false,
    showOncePolicy: 'session',
  },
  club: {
    id: 'club',
    durationMs: 1100,
    eyebrow: 'KLUB VROOM',
    title: 'CZAT KLUBOWY',
    subtitle: 'KANAŁY · CZŁONKOWIE · MODERACJA',
    bgGradient: ['#050a14', '#030303', '#050810'],
    gateLeftGradient: ['#061018', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#061018'],
    accents: { primary: COMMUNITY_ACCENTS.clubs, secondary: '#0088cc', cyan: CYAN },
    showVsRow: false,
    showGates: true,
    showClash: false,
    showOncePolicy: 'session',
  },
  market: {
    id: 'market',
    durationMs: 1000,
    eyebrow: 'GIEŁDA VROOM',
    title: 'MARKET',
    subtitle: 'KUP · SPRZEDAJ · NEGOCJUJ',
    bgGradient: ['#141008', '#030303', '#0a0805'],
    gateLeftGradient: ['#1a1400', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#1a1400'],
    accents: { primary: COMMUNITY_ACCENTS.grid, secondary: COMMUNITY_ACCENTS.duelAlt, cyan: CYAN },
    showVsRow: false,
    showGates: false,
    showClash: false,
    showOncePolicy: 'session',
  },
  'support-calm': {
    id: 'support-calm',
    durationMs: 900,
    eyebrow: 'VROOM SUPPORT',
    title: 'SUPPORT ACTIVE',
    subtitle: 'TWÓJ WĄTEK Z ZESPOŁEM',
    bgGradient: ['#050a14', '#030303', '#050810'],
    gateLeftGradient: ['#061018', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#061018'],
    accents: { primary: '#2196F3', secondary: '#1565C0', cyan: CYAN },
    showVsRow: false,
    showGates: false,
    showClash: false,
    showOncePolicy: 'session',
  },
  garage: {
    id: 'garage',
    durationMs: 1500,
    eyebrow: 'THE GRID',
    title: 'ZGŁASZASZ AUTO',
    subtitle: 'PRZYGOTUJ ZDJĘCIA I OPIS',
    bgGradient: ['#0f0a05', '#030303', '#0a0600'],
    gateLeftGradient: ['#1a1000', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#1a1000'],
    accents: { primary: COMMUNITY_ACCENTS.grid, secondary: COMMUNITY_ACCENTS.duelAlt, cyan: CYAN },
    showVsRow: false,
    showGates: true,
    showClash: false,
    showOncePolicy: 'session',
  },
  'nav-start': {
    id: 'nav-start',
    durationMs: 800,
    eyebrow: 'NAWIGACJA',
    title: 'TRASA AKTYWNA',
    subtitle: 'JEDŹ BEZPIECZNIE',
    bgGradient: ['#0a0a0a', '#030303', '#0a0a0a'],
    gateLeftGradient: ['#0a0a0a', '#060606', '#000000'],
    gateRightGradient: ['#000000', '#060606', '#0a0a0a'],
    accents: { primary: COMMUNITY_ACCENTS.duelAlt, secondary: WHITE, cyan: CYAN },
    showVsRow: false,
    showGates: false,
    showClash: false,
    showOncePolicy: 'always',
  },
};

export function getEntrancePreset(id: EntranceFxPresetId): EntranceFxPreset {
  return ENTRANCE_FX_PRESETS[id];
}
