import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useRouter } from 'expo-router';
import { useTheme } from '../contexts/ThemeContext';
import { apiRequest } from '../lib/api/client';
import * as FileSystem from 'expo-file-system/legacy';
import Toast from 'react-native-toast-message';
import { API_URL } from '../constants/config';
import { pickPremiumDocuments, sharePremiumFile } from '../lib/native/premiumNativeCapabilities';
import { ScreenCrashFallback } from '../components/ScreenCrashFallback';

export function ErrorBoundary({ retry }: { error: Error; retry: () => void }) { return <ScreenCrashFallback title="GARAŻ PRO NIE URUCHOMIŁ SIĘ" retry={retry} />; }

type Car = { id: number; brand: string; specs?: string; currentMileageKm?: number | null };
type Dashboard = { monthCostCents: number; yearCostCents: number; costPerKmCents: number | null; fuelConsumptionL100Km: number | null; upcoming: any[]; byCategory: Record<string, number> };
type Entry = { id: number; title: string; category: string; performedAt: string; costCents?: number | null; mileageKm?: number | null; attachments?: Array<{ id: string; originalName: string }> };
const CATEGORIES = ['service', 'repair', 'insurance', 'technical_review', 'fuel', 'tires', 'part', 'cost', 'custom'];

export default function PremiumGarageScreen() {
  const { theme } = useTheme(); const router = useRouter();
  const [cars, setCars] = useState<Car[]>([]); const [selected, setSelected] = useState<Car | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [entries, setEntries] = useState<Entry[]>([]); const [loading, setLoading] = useState(true); const [garageLoading, setGarageLoading] = useState(false); const [loadError, setLoadError] = useState(''); const [garageError, setGarageError] = useState(''); const [entryOpen, setEntryOpen] = useState(false);
  const [category, setCategory] = useState('service'); const [title, setTitle] = useState(''); const [cost, setCost] = useState(''); const [mileage, setMileage] = useState('');
  const [liters, setLiters] = useState(''); const [unitPrice, setUnitPrice] = useState(''); const [fullTank, setFullTank] = useState(false); const [nextDueAt, setNextDueAt] = useState(''); const [nextDueMileage, setNextDueMileage] = useState('');
  const loadCars = async () => { setLoading(true); setLoadError(''); try { const raw = await AsyncStorage.getItem('user'); const user = raw ? JSON.parse(raw) : {}; const userId = Number(user.userId ?? user.id); if (!Number.isInteger(userId) || userId <= 0) throw new Error('Nie udało się odczytać profilu użytkownika.'); const response = await apiRequest<{ items: Car[] }>(`/v2/profiles/${userId}/cars?limit=100`); setCars(response.items ?? []); if (!selected && response.items?.[0]) setSelected(response.items[0]); } catch (error: any) { setLoadError(error?.message || 'Nie udało się pobrać garażu.'); } finally { setLoading(false); } };
  useEffect(() => { void loadCars(); }, []);
  const loadGarage = async (carId: number) => { setGarageLoading(true); setGarageError(''); try { const [nextDashboard, history] = await Promise.all([apiRequest<Dashboard>(`/cars/${carId}/garage-dashboard`), apiRequest<{ entries?: Entry[] }>(`/cars/${carId}/maintenance`)]); setDashboard(nextDashboard); setEntries(Array.isArray(history?.entries) ? history.entries : []); } catch (error: any) { setDashboard(null); setEntries([]); setGarageError(error?.message || 'Nie udało się pobrać danych Garażu Pro.'); } finally { setGarageLoading(false); } };
  useEffect(() => { if (!selected) return; void loadGarage(selected.id); }, [selected?.id]);
  const addEntry = async () => { if (!selected || !title.trim()) return; const dueDate = nextDueAt ? new Date(`${nextDueAt}T12:00:00`) : null; if (dueDate && !Number.isFinite(dueDate.getTime())) { Toast.show({ type: 'error', text1: 'Nieprawidłowy termin', text2: 'Użyj formatu YYYY-MM-DD.' }); return; } await apiRequest(`/cars/${selected.id}/maintenance`, { method: 'POST', body: { category, title: title.trim(), costCents: Math.round(Number(cost.replace(',', '.')) * 100), currency: 'PLN', mileageKm: mileage ? Number(mileage) : null, liters: liters ? Number(liters.replace(',', '.')) : null, unitPriceCents: unitPrice ? Math.round(Number(unitPrice.replace(',', '.')) * 100) : null, fullTank: category === 'fuel' ? fullTank : null, nextDueAt: dueDate?.toISOString() ?? null, nextDueMileageKm: nextDueMileage ? Number(nextDueMileage) : null, performedAt: new Date().toISOString() } }); setEntryOpen(false); setTitle(''); setCost(''); setMileage(''); setLiters(''); setUnitPrice(''); setFullTank(false); setNextDueAt(''); setNextDueMileage(''); await loadGarage(selected.id); };
  const addAttachments = async (entry: Entry) => { if (!selected) return; try { const picked = await pickPremiumDocuments({ type: ['image/*', 'application/pdf'], multiple: true, copyToCacheDirectory: true }); if (picked.canceled) return; const form = new FormData(); picked.assets.slice(0, 5).forEach((asset) => form.append('files', { uri: asset.uri, name: asset.name, type: asset.mimeType || (asset.name.toLowerCase().endsWith('.pdf') ? 'application/pdf' : 'image/jpeg') } as any)); const token = (await AsyncStorage.getItem('userToken')) ?? (await AsyncStorage.getItem('token')); const response = await fetch(`${API_URL}/api/cars/${selected.id}/maintenance/${entry.id}/attachments`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: form }); if (!response.ok) throw new Error((await response.json().catch(() => ({})))?.message || 'Nie udało się dodać pliku.'); Toast.show({ type: 'success', text1: 'Dokumenty zapisane prywatnie' }); await loadGarage(selected.id); } catch (error: any) { Alert.alert('Nie można dodać dokumentu', error?.message || 'Spróbuj ponownie.'); } };
  const exportReport = async (format: 'pdf' | 'csv') => { if (!selected) return; try { const token = (await AsyncStorage.getItem('userToken')) ?? (await AsyncStorage.getItem('token')); const destination = `${FileSystem.cacheDirectory}vroom-garage-${selected.id}.${format}`; const result = await FileSystem.downloadAsync(`${API_URL}/api/cars/${selected.id}/garage-report?format=${format}`, destination, { headers: { Authorization: `Bearer ${token}` } }); if (result.status !== 200) throw new Error('Nie udało się pobrać raportu.'); await sharePremiumFile(result.uri, { mimeType: format === 'pdf' ? 'application/pdf' : 'text/csv' }); } catch (error: any) { Alert.alert('Nie można wyeksportować raportu', error?.message || 'Spróbuj ponownie.'); } };
  return <SafeAreaView style={[s.safe, { backgroundColor: theme.bg }]}><View style={s.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-back" size={24} color={theme.text} /></TouchableOpacity><Text style={[s.heading, { color: theme.text }]}>GARAŻ PRO</Text><TouchableOpacity disabled={!selected} onPress={() => setEntryOpen(true)}><MaterialIcons name="add-circle" size={26} color="#FFD447" /></TouchableOpacity></View>{loading ? <ActivityIndicator color="#FFD447" /> : <ScrollView contentContainerStyle={s.content}>
    {!!loadError && <View style={[s.panel, { borderColor: '#ff6b6b55', backgroundColor: theme.surface }]}><Text style={{ color: '#ff6b6b', textAlign: 'center' }}>{loadError}</Text><TouchableOpacity onPress={() => void loadCars()} style={s.retry}><Text style={s.retryText}>SPRÓBUJ PONOWNIE</Text></TouchableOpacity></View>}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{cars.map((car) => <TouchableOpacity key={car.id} onPress={() => setSelected(car)} style={[s.carPill, { borderColor: selected?.id === car.id ? '#FFD447' : theme.border, backgroundColor: theme.surface }]}><Text style={{ color: selected?.id === car.id ? '#FFD447' : theme.text, fontWeight: '800' }}>{car.brand}</Text><Text style={{ color: theme.textDim, fontSize: 10 }}>{car.currentMileageKm != null ? `${car.currentMileageKm} km` : 'brak przebiegu'}</Text></TouchableOpacity>)}</ScrollView>
    {!cars.length ? <Text style={{ color: theme.textDim, textAlign: 'center', marginTop: 40 }}>Dodaj auto w profilu, aby uruchomić Garaż Pro.</Text> : garageError ? <View style={[s.panel, { borderColor: '#ff6b6b55', backgroundColor: theme.surface }]}><Text style={{ color: '#ff6b6b', textAlign: 'center' }}>{garageError}</Text><TouchableOpacity onPress={() => selected && void loadGarage(selected.id)} style={s.retry}><Text style={s.retryText}>SPRÓBUJ PONOWNIE</Text></TouchableOpacity></View> : garageLoading || !dashboard ? <ActivityIndicator color="#FFD447" /> : <><View style={s.grid}><Tile label="TEN MIESIĄC" value={`${(dashboard.monthCostCents / 100).toFixed(2)} zł`} theme={theme} /><Tile label="TEN ROK" value={`${(dashboard.yearCostCents / 100).toFixed(2)} zł`} theme={theme} /><Tile label="KOSZT / KM" value={dashboard.costPerKmCents == null ? '—' : `${(dashboard.costPerKmCents / 100).toFixed(2)} zł`} theme={theme} /><Tile label="SPALANIE" value={dashboard.fuelConsumptionL100Km == null ? '—' : `${dashboard.fuelConsumptionL100Km.toFixed(1)} l/100`} theme={theme} /></View><View style={s.reportRow}><TouchableOpacity onPress={() => void exportReport('pdf')} style={s.report}><Text style={s.reportText}>RAPORT PDF</Text></TouchableOpacity><TouchableOpacity onPress={() => void exportReport('csv')} style={s.report}><Text style={s.reportText}>EKSPORT CSV</Text></TouchableOpacity></View><View style={[s.panel, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[s.label, { color: theme.text }]}>NADCHODZĄCE TERMINY</Text>{dashboard.upcoming?.length ? dashboard.upcoming.map((item, index) => <Text key={index} style={{ color: theme.textDim, marginTop: 8 }}>{item.title ?? item.category} · {item.nextDueAt ? new Date(item.nextDueAt).toLocaleDateString('pl-PL') : `${item.nextDueMileageKm} km`}</Text>) : <Text style={{ color: theme.textDim, marginTop: 8 }}>Brak nadchodzących terminów.</Text>}</View><View style={[s.panel, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[s.label, { color: theme.text }]}>HISTORIA I DOKUMENTY</Text>{entries.length ? entries.map((entry) => <View key={entry.id} style={[s.entry, { borderColor: theme.border }]}><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '800' }}>{entry.title}</Text><Text style={{ color: theme.textDim, fontSize: 9, marginTop: 3 }}>{new Date(entry.performedAt).toLocaleDateString('pl-PL')} · {entry.category} · {entry.attachments?.length || 0}/5 plików</Text></View><TouchableOpacity onPress={() => void addAttachments(entry)}><MaterialIcons name="attach-file" size={22} color="#FFD447" /></TouchableOpacity></View>) : <Text style={{ color: theme.textDim, marginTop: 10 }}>Nie masz jeszcze wpisów. Użyj przycisku +, aby dodać pierwszy serwis, tankowanie lub koszt.</Text>}</View></>}
  </ScrollView>}
  <Modal visible={entryOpen} transparent animationType="slide" onRequestClose={() => setEntryOpen(false)}><View style={s.backdrop}><View style={[s.modal, { backgroundColor: theme.surface }]}><ScrollView keyboardShouldPersistTaps="handled"><Text style={[s.heading, { color: theme.text }]}>NOWY WPIS</Text><ScrollView horizontal contentContainerStyle={{ gap: 6, paddingVertical: 12 }}>{CATEGORIES.map((value) => <TouchableOpacity key={value} onPress={() => setCategory(value)} style={[s.category, { borderColor: category === value ? '#FFD447' : theme.border }]}><Text style={{ color: category === value ? '#FFD447' : theme.textDim, fontSize: 9 }}>{value}</Text></TouchableOpacity>)}</ScrollView><Input value={title} onChangeText={setTitle} placeholder="Nazwa wpisu" theme={theme} /><Input value={cost} onChangeText={setCost} placeholder="Koszt w zł" theme={theme} keyboardType="decimal-pad" /><Input value={mileage} onChangeText={setMileage} placeholder="Przebieg km" theme={theme} keyboardType="number-pad" />{category === 'fuel' && <><Input value={liters} onChangeText={setLiters} placeholder="Liczba litrów" theme={theme} keyboardType="decimal-pad" /><Input value={unitPrice} onChangeText={setUnitPrice} placeholder="Cena za litr" theme={theme} keyboardType="decimal-pad" /><View style={s.switchRow}><Text style={{ color: theme.text, flex: 1 }}>Tankowanie do pełna</Text><Switch value={fullTank} onValueChange={setFullTank} /></View></>}<Input value={nextDueAt} onChangeText={setNextDueAt} placeholder="Kolejny termin YYYY-MM-DD" theme={theme} /><Input value={nextDueMileage} onChangeText={setNextDueMileage} placeholder="Kolejny przebieg km" theme={theme} keyboardType="number-pad" /><TouchableOpacity onPress={() => void addEntry()} style={s.primary}><Text style={s.primaryText}>ZAPISZ WPIS</Text></TouchableOpacity><TouchableOpacity onPress={() => setEntryOpen(false)}><Text style={[s.cancel, { color: theme.textDim }]}>ANULUJ</Text></TouchableOpacity></ScrollView></View></View></Modal>
  </SafeAreaView>;
}
function Tile({ label, value, theme }: any) { return <View style={[s.tile, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[s.value, { color: theme.text }]}>{value}</Text><Text style={[s.tileLabel, { color: theme.textDim }]}>{label}</Text></View>; }
function Input(props: any) { const { theme, ...rest } = props; return <TextInput {...rest} placeholderTextColor={theme.textDim} style={[s.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.bg }]} />; }
const s = StyleSheet.create({ safe: { flex: 1 }, header: { height: 56, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, heading: { fontFamily: 'OrbitronBold', fontSize: 14, letterSpacing: 2 }, content: { padding: 16, gap: 16 }, carPill: { minWidth: 130, borderWidth: 1, borderRadius: 14, padding: 12, gap: 4 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, tile: { width: '48%', borderWidth: 1, borderRadius: 15, padding: 15 }, value: { fontSize: 16, fontWeight: '900' }, tileLabel: { fontSize: 8, marginTop: 6 }, panel: { borderWidth: 1, borderRadius: 16, padding: 16 }, retry: { alignSelf: 'center', marginTop: 12, backgroundColor: '#FFD447', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10 }, retryText: { color: '#111', fontSize: 9, fontWeight: '900' }, label: { fontFamily: 'Orbitron', fontSize: 10, fontWeight: '900' }, entry: { minHeight: 54, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', marginTop: 7 }, reportRow: { flexDirection: 'row', gap: 8 }, report: { flex: 1, minHeight: 44, borderRadius: 11, backgroundColor: '#FFD447', alignItems: 'center', justifyContent: 'center' }, reportText: { color: '#111', fontWeight: '900', fontSize: 9 }, backdrop: { flex: 1, backgroundColor: '#000a', justifyContent: 'flex-end' }, modal: { maxHeight: '90%', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 36 }, switchRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', marginTop: 8 }, category: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 8 }, input: { borderWidth: 1, borderRadius: 12, padding: 13, marginTop: 10 }, primary: { backgroundColor: '#FFD447', minHeight: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 14 }, primaryText: { color: '#111', fontWeight: '900' }, cancel: { textAlign: 'center', padding: 14, fontWeight: '700' } });
