import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useRouter } from 'expo-router';
import { API_URL } from '../../constants/config';
import { useTheme } from '../../contexts/ThemeContext';
import { useScreenHeaderTop } from '../../lib/screenHeaderInsets';

type Stats = { points: number; distanceKm: number; ridesCount: number; driveSeconds: number; avgSpeed: number; maxSpeed: number; maxStreak: number; spotsCreated: number; citiesDiscovered: number; meetsJoined: number; achievementsUnlocked: number; finalPosition?: number | null };
type RewardGrant = { id: string; status: string; position: number; claimBy?: string | null; reward: { name: string; type: string }; season: { number: number; name: string } };
const emptyAddress = { fullName: '', phone: '', street: '', postalCode: '', city: '', country: 'Polska' };
const duration = (seconds = 0) => `${Math.floor(seconds / 3600)} h ${Math.floor((seconds % 3600) / 60)} min`;

export default function SeasonStatsScreen() {
  const { theme } = useTheme(); const router = useRouter(); const top = useScreenHeaderTop(8);
  const [current, setCurrent] = useState<any>(null); const [history, setHistory] = useState<any[]>([]); const [rewards, setRewards] = useState<RewardGrant[]>([]);
  const [loading, setLoading] = useState(true); const [claimId, setClaimId] = useState<string | null>(null); const [address, setAddress] = useState(emptyAddress); const [message, setMessage] = useState('');
  const api = useCallback(async (path: string, options?: RequestInit) => { const token = (await AsyncStorage.getItem('token')) ?? (await AsyncStorage.getItem('userToken')); const response = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options?.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); return data; }, []);
  const load = useCallback(async () => { setLoading(true); try { const [now, past, grants] = await Promise.all([api('/api/seasons/current'), api('/api/seasons/history'), api('/api/seasons/rewards')]); setCurrent(now); setHistory(past); setRewards(grants); } catch (error) { setMessage(error instanceof Error ? error.message : 'Błąd pobierania'); } finally { setLoading(false); } }, [api]);
  useEffect(() => { void load(); }, [load]);
  const claim = async () => { if (!claimId) return; try { await api(`/api/seasons/rewards/${claimId}/claim`, { method: 'POST', body: JSON.stringify({ shippingAddress: address }) }); setMessage('Dane zapisane. Nagroda trafiła do kolejki wysyłki.'); setClaimId(null); setAddress(emptyAddress); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Nie udało się zapisać danych'); } };
  const StatGrid = ({ stats }: { stats?: Stats | null }) => stats ? <View style={styles.grid}>{[
    ['Punkty', stats.points, 'star-circle'], ['Kilometry', Number(stats.distanceKm || 0).toFixed(1), 'map-marker-distance'], ['Przejazdy', stats.ridesCount, 'car'], ['Czas jazdy', duration(stats.driveSeconds), 'clock-outline'], ['Śr. prędkość', `${Number(stats.avgSpeed || 0).toFixed(1)} km/h`, 'speedometer-medium'], ['Maks. prędkość', `${Number(stats.maxSpeed || 0).toFixed(0)} km/h`, 'speedometer'], ['Najlepszy streak', stats.maxStreak, 'fire'], ['Spoty', stats.spotsCreated, 'map-marker-plus'], ['Miasta', stats.citiesDiscovered, 'city'], ['Meety', stats.meetsJoined, 'calendar-star'], ['Odznaki', stats.achievementsUnlocked, 'medal'], ['Pozycja', stats.finalPosition ? `#${stats.finalPosition}` : '—', 'podium'],
  ].map(([label, value, icon]) => <View key={String(label)} style={[styles.stat, { backgroundColor: theme.surface, borderColor: theme.border }]}><MaterialCommunityIcons name={icon as any} size={18} color={theme.primary} /><Text style={[styles.value, { color: theme.text }]}>{String(value)}</Text><Text style={[styles.label, { color: theme.textDim }]}>{label}</Text></View>)}</View> : <Text style={[styles.empty, { color: theme.textDim }]}>Brak aktywności w tym sezonie.</Text>;
  return <View style={{ flex: 1, backgroundColor: theme.bg }}><View style={[styles.header, { paddingTop: top, borderBottomColor: theme.border }]}><TouchableOpacity onPress={() => router.back()}><MaterialCommunityIcons name="arrow-left" size={25} color={theme.text} /></TouchableOpacity><View><Text style={[styles.title, { color: theme.text }]}>SEZONY VROOM</Text><Text style={[styles.subtitle, { color: theme.textDim }]}>STATYSTYKI · HISTORIA · NAGRODY</Text></View></View>{loading ? <ActivityIndicator style={{ flex: 1 }} color={theme.primary} /> : <ScrollView contentContainerStyle={styles.content}>
    {message ? <Text style={[styles.message, { color: theme.primary }]}>{message}</Text> : null}
    <Text style={[styles.section, { color: theme.textDim }]}>BIEŻĄCY SEZON</Text>{current?.season ? <View><Text style={[styles.seasonName, { color: theme.text }]}>S{current.season.number} · {current.season.name}</Text><Text style={[styles.date, { color: theme.textDim }]}>Kończy się {new Date(current.season.endsAt).toLocaleString('pl-PL')}</Text><StatGrid stats={current.stats} /></View> : <Text style={[styles.empty, { color: theme.textDim }]}>Obecnie nie trwa żaden sezon.</Text>}
    <Text style={[styles.section, { color: theme.textDim }]}>MOJE NAGRODY</Text>{rewards.map((grant) => <View key={grant.id} style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><MaterialCommunityIcons name={grant.reward.type === 'shop_product' ? 'package-variant' : 'gift'} size={24} color="#FFD447" /><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: theme.text }]}>{grant.reward.name}</Text><Text style={[styles.date, { color: theme.textDim }]}>S{grant.season.number} · miejsce #{grant.position} · {grant.status}</Text></View>{grant.status === 'awaiting_claim' && <TouchableOpacity onPress={() => setClaimId(grant.id)} style={[styles.claim, { backgroundColor: theme.primary }]}><Text style={styles.claimText}>ODBIERZ</Text></TouchableOpacity>}</View>)}
    {claimId && <View style={[styles.form, { backgroundColor: theme.surface, borderColor: theme.primary }]}><Text style={[styles.cardTitle, { color: theme.text }]}>Dane do wysyłki</Text>{Object.keys(address).map((key) => <TextInput key={key} value={(address as any)[key]} placeholder={key} placeholderTextColor={theme.textDim} onChangeText={(value) => setAddress((prev) => ({ ...prev, [key]: value }))} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.bg }]} />)}<TouchableOpacity onPress={claim} style={[styles.submit, { backgroundColor: theme.primary }]}><Text style={styles.claimText}>POTWIERDŹ DANE</Text></TouchableOpacity></View>}
    <Text style={[styles.section, { color: theme.textDim }]}>HISTORIA</Text>{history.map((season) => <View key={season.id} style={{ marginBottom: 24 }}><Text style={[styles.seasonName, { color: theme.text }]}>S{season.number} · {season.name}</Text><Text style={[styles.date, { color: theme.textDim }]}>{season.status === 'cancelled' ? 'Anulowany' : `Pozycja ${season.myStats?.finalPosition ? `#${season.myStats.finalPosition}` : '—'}`}</Text><StatGrid stats={season.myStats} />{season.winners?.length > 0 && <View style={[styles.archiveBox, { borderColor: theme.border }]}><Text style={[styles.archiveTitle, { color: theme.text }]}>PODIUM</Text>{season.winners.map((winner: any) => <Text key={winner.id} style={[styles.archiveLine, { color: theme.textDim }]}>#{winner.finalPosition} {winner.user.username} · {winner.points} pkt</Text>)}</View>}{season.rewards?.length > 0 && <View style={[styles.archiveBox, { borderColor: theme.border }]}><Text style={[styles.archiveTitle, { color: theme.text }]}>NAGRODY</Text>{season.rewards.map((reward: any) => <Text key={reward.id} style={[styles.archiveLine, { color: theme.textDim }]}>#{reward.placeFrom}{reward.placeTo !== reward.placeFrom ? `–${reward.placeTo}` : ''} · {reward.name}</Text>)}</View>}{season.achievementDefinitions?.length > 0 && <View style={[styles.archiveBox, { borderColor: theme.border }]}><Text style={[styles.archiveTitle, { color: theme.text }]}>OSIĄGNIĘCIA</Text>{season.achievementDefinitions.map((achievement: any) => <Text key={achievement.id} style={[styles.archiveLine, { color: theme.textDim }]}>{achievement.icon} {achievement.label}</Text>)}</View>}</View>)}
  </ScrollView>}</View>;
}

const styles = StyleSheet.create({ header: { minHeight: 72, paddingHorizontal: 16, paddingBottom: 13, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 14 }, title: { fontFamily: 'Orbitron', fontSize: 15, fontWeight: '900' }, subtitle: { fontFamily: 'Orbitron', fontSize: 7, letterSpacing: 1.2, marginTop: 3 }, content: { padding: 16, paddingBottom: 60 }, section: { fontFamily: 'Orbitron', fontSize: 9, fontWeight: '900', letterSpacing: 1.5, marginTop: 12, marginBottom: 12 }, seasonName: { fontFamily: 'Orbitron', fontSize: 15, fontWeight: '900' }, date: { fontFamily: 'Satoshi', fontSize: 11, marginTop: 4 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }, stat: { width: '31%', minHeight: 88, borderWidth: 1, borderRadius: 14, padding: 10, justifyContent: 'space-between' }, value: { fontFamily: 'Orbitron', fontSize: 13, fontWeight: '900' }, label: { fontFamily: 'Satoshi', fontSize: 10 }, empty: { fontFamily: 'Satoshi', fontSize: 13, marginVertical: 8 }, card: { borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }, cardTitle: { fontFamily: 'Orbitron', fontSize: 11, fontWeight: '900' }, claim: { borderRadius: 9, paddingHorizontal: 10, paddingVertical: 8 }, claimText: { color: '#fff', fontFamily: 'Orbitron', fontSize: 8, fontWeight: '900' }, form: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8, marginVertical: 10 }, input: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, minHeight: 42, fontFamily: 'Satoshi' }, submit: { borderRadius: 10, padding: 13, alignItems: 'center' }, message: { fontFamily: 'Satoshi', fontSize: 12, marginBottom: 8 }, archiveBox: { borderTopWidth: 1, marginTop: 12, paddingTop: 9, gap: 4 }, archiveTitle: { fontFamily: 'Orbitron', fontSize: 8, fontWeight: '900', letterSpacing: 1 }, archiveLine: { fontFamily: 'Satoshi', fontSize: 11 } });
