/** V3 navigation constants — keep in sync with snapEngine + useDriveMarkerV3. */
export const NAV_V3 = {
  MARKER_MAX_HEADING_DPS: 90,
  MARKER_MIN_CRUISE_MS: 0.5,
  SNAP_ATTACH_M: 12,
  SNAP_DETACH_START_M: 18,
  SNAP_DETACH_FULL_M: 45,
  SNAP_MAX_RADIUS_M: 80,
  BRANCH_HEADING_DELTA_DEG: 35,
  BRANCH_CONFIRM_TICKS: 3,
  BRANCH_HEADING_CONFIRM_TOLERANCE_DEG: 20,
  ON_ROAD_BLEND_EPS: 0.05,
  CAMERA_FOLLOW_INTERVAL_MS: 16,
  CAMERA_MAX_HEADING_DPS: 95,
  GPS_IMPOSSIBLE_JUMP_M: 150,
  GPS_IMPOSSIBLE_JUMP_MAX_KMH: 300,
  GPS_MAX_ACCURACY_REJECT_M: 120,
  GPS_MIN_MOVING_SPEED_MS: 0.55,
  GPS_MOVING_MIN_STEP_M: 2.5,
  PIPELINE_MOVING_KMH: 3,
} as const;

export type NavV3Config = typeof NAV_V3;
