import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // ========== CONTAINERS ==========
  container: {
    flex: 1,
    backgroundColor: "#0f0f0f",
  },
  mapContainer: {
    flex: 1,
    position: 'relative',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0f0f0f',
  },

  // ========== MARKERS ==========
  carMarker: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#1a1a1a',
    borderWidth: 2,
    borderColor: '#e33835ce',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ✅ USER CAR MARKER – naprawione
  userCarMarkerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 4,
  },
  userCarMarkerLabel: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    backgroundColor: '#0f0f0fcc',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 2,
    textAlign: 'center',
  },
  userCarMarkerDistance: {
    color: '#e33835ce',
    fontSize: 9,
    fontWeight: '600',
    backgroundColor: '#0f0f0fcc',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 4,
    textAlign: 'center',
  },
  userCarMarker: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 5,
  },

  userMarker: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e33835ce',
    alignItems: 'center',
  },
  userMarkerText: {
    fontSize: 18,
    marginBottom: 2,
  },
  userMarkerName: {
    fontSize: 9,
    color: '#fff',
    fontWeight: 'bold',
  },
  userMarkerDistance: {
    fontSize: 8,
    color: '#e33835ce',
    fontWeight: '600',
    marginTop: 1,
  },

  // ========== SPEED PANEL ==========
  speedPanelNav: {
    position: 'absolute',
    bottom: 20,
    left: 15,
    backgroundColor: '#e33835ce',
    borderRadius: 20,
    padding: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    zIndex: 30,
  },
  speedValue: {
    color: '#0f0f0f',
    fontSize: 18,
    fontWeight: 'bold',
  },
  speedLabel: {
    color: '#0f0f0f',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // ========== CONTROLS ==========
  rightBottomControls: {
    position: 'absolute',
    right: 15,
    bottom: 20,
    gap: 12,
    zIndex: 100,
  },
  sideBtn: {
    backgroundColor: '#1d2c4d',
    width: 48,
    height: 48,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#283d6a',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },

  // ========== TOP SEARCH BUTTON ==========
  topSearchButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 45,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a1a1ad9',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#ffffff20',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    zIndex: 10,
  },
  topSearchButtonText: {
    color: '#ffffff70',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
    marginHorizontal: 8,
  },

  // ========== SEARCH MODAL ==========
  searchModalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  searchModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#00000080',
  },
  searchModalContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    maxHeight: height * 0.9,
    backgroundColor: '#0f0f0f',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingTop: Platform.OS === 'ios' ? 16 : 12,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    zIndex: 12,
  },
  searchModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchModalBackBtn: {
    padding: 8,
  },
  searchModalTitle: {
    color: '#e33835ce',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  searchModalTabs: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    gap: 12,
    marginBottom: 12,
  },
  searchModalTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#ffffff08',
    borderWidth: 1,
    borderColor: '#ffffff15',
  },
  searchModalTabActive: {
    backgroundColor: '#e3383515',
    borderColor: '#e33835ce',
  },
  searchModalTabText: {
    color: '#ffffff70',
    fontSize: 12,
    fontWeight: '600',
  },
  searchModalTabTextActive: {
    color: '#e33835ce',
    fontWeight: 'bold',
  },
  searchModalDivider: {
    height: 1,
    backgroundColor: '#ffffff15',
    marginHorizontal: 12,
    marginBottom: 12,
  },
  searchModalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginHorizontal: 12,
    marginBottom: 8,
    backgroundColor: '#ffffff08',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ffffff15',
    gap: 8,
  },
  searchModalInput: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
    paddingVertical: 4,
  },
  searchHelperText: {
    color: '#ffffff50',
    fontSize: 11,
    paddingHorizontal: 12,
    marginBottom: 12,
    fontStyle: 'italic',
  },
  searchResultsList: {
    marginHorizontal: 12,
    marginBottom: 12,
    maxHeight: height * 0.65,
    borderRadius: 10,
    backgroundColor: '#ffffff08',
    borderWidth: 1,
    borderColor: '#ffffff15',
    overflow: 'hidden',
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ffffff10',
  },
  searchResultIconCurrent: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#e3383515',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchResultIconUser: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#ffffff08',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchResultIconPlace: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#ffffff08',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchResultUserAvatar: {
    fontSize: 20,
  },
  searchResultItemText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  searchResultMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  userStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  searchResultMetaText: {
    color: '#ffffff70',
    fontSize: 11,
  },

  // ========== CATEGORIES GRID ==========
  categoriesGrid: {
    flexDirection: 'column',
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  categoryCard: {
    backgroundColor: '#ffffff08',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffffff15',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  categoryIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#ffffff08',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff15',
  },
  categoryTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  categorySubtitle: {
    color: '#ffffff70',
    fontSize: 12,
    marginTop: 2,
  },
  emptyList: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  emptyListText: {
    color: '#ffffff70',
    fontSize: 12,
    textAlign: 'center',
  },

  // ========== NAVIGATION PANEL ==========
  navigationPanelTop: {
    position: 'absolute',
    top: Platform.OS === "ios" ? 65 : 50,
    left: 12,
    right: 12,
    backgroundColor: '#1a1a1ad9',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e3383544',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    zIndex: 13,
  },
  instructionBox: {
    paddingRight: 35,
  },
  instructionDistance: {
    color: '#e33835ce',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  instructionText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  stepCounter: {
    color: '#ffffff70',
    fontSize: 10,
    marginTop: 4,
  },
  closeNavBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
  },

  // ========== USER INFO MODAL ==========
  userInfoOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  userInfoBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#00000080',
  },
  userInfoCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1a1a1a',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderColor: '#ffffff20',
    paddingVertical: 24,
    paddingHorizontal: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  userInfoHeader: {
    alignItems: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  userInfoAvatar: {
    fontSize: 64,
    marginBottom: 12,
  },
  userInfoCloseBtn: {
    position: 'absolute',
    top: -8,
    right: 0,
    padding: 8,
  },
  userInfoContent: {
    marginBottom: 20,
    alignItems: 'center',
    width: '100%',
  },
  userInfoName: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  userInfoStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  userInfoStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  userInfoStatus: {
    color: '#ffffff70',
    fontSize: 12,
    fontWeight: '500',
  },
  userInfoDivider: {
    height: 1,
    width: '100%',
    backgroundColor: '#ffffff15',
    marginBottom: 16,
  },
  userInfoStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    width: '100%',
  },
  userInfoStatIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#e3383515',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userInfoStatLabel: {
    color: '#ffffff70',
    fontSize: 11,
    marginBottom: 2,
  },
  userInfoStatValue: {
    color: '#e33835ce',
    fontSize: 14,
    fontWeight: 'bold',
  },
  userInfoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#ff6b9d15',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ff6b9d40',
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  userInfoBadgeText: {
    color: '#ff6b9d',
    fontSize: 12,
    fontWeight: '600',
  },
  userInfoNavigateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    backgroundColor: '#e33835ce',
    borderRadius: 12,
    elevation: 3,
    shadowColor: '#e33835ce',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  userInfoNavigateBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },

  // ========== BOTTOM SHEET ==========
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1a1a1a',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#ffffff20',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    paddingBottom: 24,
  },
  expandHandle: {
    width: 36,
    height: 3,
    backgroundColor: '#ffffff40',
    borderRadius: 2,
    alignSelf: 'center',
    marginVertical: 12,
  },
  infoPreview: {
    paddingHorizontal: 12,
  },
  routeInfoCard: {
    backgroundColor: '#ffffff08',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffffff15',
    marginBottom: 12,
    overflow: 'hidden',
  },
  routeInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  routeInfoLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  routeInfoDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ffffff40',
  },
  routeInfoLocationName: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  routeInfoDivider: {
    height: 1,
    backgroundColor: '#ffffff10',
    marginHorizontal: 12,
  },
  routeStatsRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff08',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffffff15',
    marginBottom: 12,
    overflow: 'hidden',
  },
  statItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  statIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#e3383515',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statLabel: {
    color: '#ffffff70',
    fontSize: 10,
    fontWeight: '500',
    marginBottom: 2,
  },
  statValue: {
    color: '#e33835ce',
    fontSize: 13,
    fontWeight: 'bold',
  },
  statDivider: {
    width: 1,
    backgroundColor: '#ffffff10',
  },
  bottomSheetButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  navigateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    backgroundColor: '#e33835ce',
    borderRadius: 10,
    elevation: 3,
    shadowColor: '#e33835ce',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  navigateButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  editButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff08',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e33835ce',
  },
  editButtonText: {
    color: '#e33835ce',
    fontSize: 12,
    fontWeight: 'bold',
  },
  resetButtonSmall: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff08',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ffffff15',
  },

  // ========== EMPTY STATE ==========
  emptyStateContainer: {
    position: 'absolute',
    bottom: -5,
    width: '102%',
    left: -5,
    right: 0,
    height: 180,
    backgroundColor: '#0f0f0f',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderTopWidth: 1,
    borderColor: '#ffffff20',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 24,

  },
  emptyState: {
    alignItems: 'center',
    gap: 12,
  },
  emptyTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  emptySubtitle: {
    color: '#ffffff70',
    fontSize: 12,
    textAlign: 'center',
    marginHorizontal: 24,
  },

  // ========== DRAWER MODAL ==========
  drawerModalContainer: {
    flex: 1,
    backgroundColor: '#00000099',
    justifyContent: 'flex-end',
  },
  drawerModal: {
    backgroundColor: '#1a1a1a',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderTopColor: '#ffffff20',
    padding: 24,
    paddingBottom: 36,
    minHeight: 250,
  },
  drawerTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 16,
  },
  drawerBtn: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 10,
    backgroundColor: '#ffffff08',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#ffffff15',
  },
  drawerBtnIcon: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#ffffff40',
    justifyContent: 'center',
    alignItems: 'center',
  },
  drawerBtnIconInner: {
    width: 8,
    height: 8,
    borderRadius: 2,
    backgroundColor: '#fff',
  },
  drawerBtnTxt: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  drawerCloseBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 8,
    zIndex: 15,
  },

  // ========== REPORT ==========
  reportItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 14,
    backgroundColor: '#ffffff08',
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#ffffff15',
  },
  reportItemText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 12,
    flex: 1,
  },
});