import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import Mapbox from '@rnmapbox/maps';
import ViewShot, { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';
import { useTheme } from '../../contexts/ThemeContext';
import { apiRequest } from '../../lib/api/client';
import { resolveStandardMapStyle } from '../../constants/mapConfig';
import { initMapbox } from '../../lib/mapboxInit';

type Point = { latitude: number; longitude: number; speedKmh?: number | null; altitudeM?: number | null };
type ReplayAvailability = { route?: boolean; timeline?: boolean; speedChart?: boolean; speedHeatmap?: boolean; elevationChart?: boolean; stops?: boolean; events?: boolean; comparison?: boolean };
type Replay = { activity: { id: number; distance: number; duration: number; avgSpeed: number; maxSpeed: number; routePoints: Point[]; insight?: any }; previous?: any; previousSimilarity?: number; availability?: ReplayAvailability; privacyDefaults: any };
const distanceM = (a: Point, b: Point) => { const r = 6371000; const dLat = (b.latitude - a.latitude) * Math.PI / 180; const dLon = (b.longitude - a.longitude) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(a.latitude * Math.PI / 180) * Math.cos(b.latitude * Math.PI / 180) * Math.sin(dLon / 2) ** 2; return 2 * r * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); };
function trimEndpoints(points: Point[], metres: number) { let start = 0; let travelled = 0; while (start < points.length - 1 && travelled < metres) { travelled += distanceM(points[start], points[start + 1]); start += 1; } let end = points.length - 1; travelled = 0; while (end > start && travelled < metres) { travelled += distanceM(points[end], points[end - 1]); end -= 1; } return points.slice(start, Math.max(start + 2, end + 1)); }

export default function ReplayScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { theme, isDark, presetId } = useTheme();
  const [data, setData] = useState<Replay | null>(null);
  const [error, setError] = useState('');
  const [rendering, setRendering] = useState(false);
  const [renderError, setRenderError] = useState('');
  const [asset, setAsset] = useState<any | null>(null);
  const [showSpeed, setShowSpeed] = useState(false);
  const [fullRoute, setFullRoute] = useState(false);
  const [playhead, setPlayhead] = useState(0);
  const [playing, setPlaying] = useState(true);
  const [playbackRate, setPlaybackRate] = useState(1);
  const [capturing, setCapturing] = useState(false);
  const shareCard = useRef<ViewShot>(null);
  useEffect(() => { void initMapbox().catch(() => setError('Nie udało się uruchomić mapy Replay.')); }, []);
  useEffect(() => { apiRequest<Replay>(`/activity/history/${id}/replay`).then(setData).catch((e) => setError(e.message)); }, [id]);
  useEffect(() => { if (data) { setPlayhead(0); setPlaying(true); } }, [data]);
  useEffect(() => { if (!data || !playing) return undefined; const timer = setInterval(() => setPlayhead((value) => { const next = value + (100 / 15_000) * playbackRate; if (next >= 1) { setPlaying(false); return 1; } return next; }), 100); return () => clearInterval(timer); }, [data, playbackRate, playing]);
  const visiblePoints = useMemo(() => { const points = data?.activity.routePoints ?? []; return capturing && !fullRoute ? trimEndpoints(points, 500) : points; }, [capturing, data, fullRoute]);
  const coordinates = useMemo(() => visiblePoints.map((p) => [p.longitude, p.latitude]), [visiblePoints]);
  const canShowSpeedHeatmap = data?.availability?.speedHeatmap === true;
  const shape = useMemo(() => ({ type: 'FeatureCollection', features: visiblePoints.slice(0, -1).map((point, index) => { const next = visiblePoints[index + 1]; const speeds = [point.speedKmh, next?.speedKmh].map(Number).filter(Number.isFinite); return { type: 'Feature', properties: { speed: speeds.length ? speeds.reduce((sum, value) => sum + value, 0) / speeds.length : null }, geometry: { type: 'LineString', coordinates: [[point.longitude, point.latitude], [next.longitude, next.latitude]] } }; }) }) as any, [visiblePoints]);
  const exportPng = async () => { let uri = ''; setCapturing(true); try { await new Promise((resolve) => setTimeout(resolve, 120)); uri = await captureRef(shareCard, { format: 'png', quality: 1, width: 1080, height: 1350 }); } finally { setCapturing(false); } if (uri && await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: 'image/png' }); };
  useEffect(() => { if (!asset?.id || !['queued', 'processing'].includes(asset.status)) return; let cancelled = false; const poll = () => apiRequest<any>(`/activity/replay-assets/${asset.id}`).then((response) => { if (!cancelled) { setAsset(response.asset); setRenderError(response.asset?.status === 'failed' ? response.asset?.error || 'Renderowanie nie powiodło się.' : ''); } }).catch((e) => { if (!cancelled) setRenderError(e?.message || 'Nie udało się sprawdzić stanu renderu.'); }); poll(); const timer = setInterval(poll, 2500); return () => { cancelled = true; clearInterval(timer); }; }, [asset?.id, asset?.status]);
  const renderMp4 = async () => { setRendering(true); setRenderError(''); try { const response = await apiRequest<any>(`/activity/history/${id}/replay/mp4`, { method: 'POST', body: { showSpeed: canShowSpeedHeatmap && showSpeed, fullRoute } }); setAsset(response.asset); } catch (e: any) { setRenderError(e.message); } finally { setRendering(false); } };
  const publish = async () => { if (!asset?.id) return; setRendering(true); try { const response = await apiRequest<any>(`/activity/replay-assets/${asset.id}/publish-vroomki`, { method: 'POST', body: { confirmed: true } }); setAsset((current: any) => ({ ...current, publishedPostId: response.postId })); Alert.alert('VROOMKA jest przygotowywana', 'Film przechodzi przez bezpieczny system mediów. Miniatura i post pojawią się po zakończeniu przetwarzania.'); } catch (e: any) { setError(e.message); } finally { setRendering(false); } };
  const deletePublished = () => { if (!asset?.id) return; Alert.alert('Usunąć VROOMKĘ?', 'Film publiczny i miniatura zostaną usunięte. Prywatny przejazd zostanie w historii.', [{ text: 'Anuluj', style: 'cancel' }, { text: 'Usuń', style: 'destructive', onPress: async () => { try { await apiRequest(`/activity/replay-assets/${asset.id}/published-vroomki`, { method: 'DELETE' }); setAsset((current: any) => ({ ...current, publishedPostId: null })); } catch (e: any) { setError(e.message); } } }]); };
  if (!data) return <SafeAreaView style={[styles.safe, { backgroundColor: theme.bg }]}>{error ? <Text style={[styles.error, { color: theme.text }]}>{error}</Text> : <ActivityIndicator color="#FFD447" style={{ marginTop: 50 }} />}</SafeAreaView>;
  const first = coordinates[0];
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.bg }]}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><MaterialIcons name="arrow-back" size={24} color={theme.text} /></TouchableOpacity><Text style={[styles.title, { color: theme.text }]}>DRIVE REPLAY</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content}>
    <ViewShot ref={shareCard} style={[styles.card, { backgroundColor: theme.surface }]} options={{ format: 'png', quality: 1 }}>
      <View style={styles.map}>{first && <Mapbox.MapView style={{ flex: 1 }} styleURL={resolveStandardMapStyle(isDark, presetId)} logoEnabled={false} attributionEnabled={false}><Mapbox.Camera defaultSettings={{ centerCoordinate: first, zoomLevel: 11 }} /><Mapbox.ShapeSource id="replay-route" shape={shape}><Mapbox.LineLayer id="replay-line" style={{ lineColor: canShowSpeedHeatmap && (!capturing || showSpeed) ? ['interpolate', ['linear'], ['get', 'speed'], 0, '#4de926', 70, '#FFD447', 140, '#e33835'] as any : '#FFD447', lineWidth: 6, lineCap: 'round' }} /></Mapbox.ShapeSource>{coordinates.length > 0 && <Mapbox.PointAnnotation id="replay-playhead" coordinate={coordinates[Math.min(coordinates.length - 1, Math.floor(playhead * (coordinates.length - 1)))] as [number, number]}><View style={styles.marker} /></Mapbox.PointAnnotation>}</Mapbox.MapView>}</View>
      <Text style={styles.brand}>VROOM · DRIVE REPLAY</Text><View style={styles.stats}><Stat label="DYSTANS" value={`${Number(data.activity.distance || 0).toFixed(1)} km`} /><Stat label="CZAS" value={`${Math.round(Number(data.activity.duration || 0) / 60)} min`} /><Stat label="ŚREDNIA" value={!capturing || showSpeed ? `${Number(data.activity.avgSpeed || 0).toFixed(1)} km/h` : 'UKRYTA'} /></View>
      <View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${playhead * 100}%` as any }]} /></View>
    </ViewShot>
    <View style={[styles.insight, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={styles.controls}><TouchableOpacity onPress={() => { if (playhead >= 1) setPlayhead(0); setPlaying((value) => !value); }}><MaterialIcons name={playing ? 'pause' : 'play-arrow'} size={25} color="#FFD447" /></TouchableOpacity><TouchableOpacity onPress={() => { setPlayhead(0); setPlaying(true); }}><MaterialIcons name="replay" size={23} color={theme.text} /></TouchableOpacity>{[0.5, 1, 2].map((rate) => <TouchableOpacity key={rate} onPress={() => setPlaybackRate(rate)} style={[styles.rate, { borderColor: playbackRate === rate ? '#FFD447' : theme.border }]}><Text style={{ color: playbackRate === rate ? '#FFD447' : theme.textDim, fontSize: 9, fontWeight: '900' }}>{rate}×</Text></TouchableOpacity>)}</View></View>
    <View style={[styles.insight, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[styles.section, { color: theme.text }]}>ANALIZA</Text>{data.availability?.timeline ? <Text style={[styles.meta, { color: theme.textDim }]}>Ruch: {Math.round((data.activity.insight?.movingDurationSec ?? 0) / 60)} min · postój: {Math.round((data.activity.insight?.stoppedDurationSec ?? 0) / 60)} min</Text> : <Text style={[styles.meta, { color: theme.textDim }]}>Ten przejazd nie zapisał osi czasu GPS, dlatego nie pokazujemy zmyślonych danych ruchu i postoju.</Text>}{data.availability?.elevationChart || data.availability?.events ? <Text style={[styles.meta, { color: theme.textDim }]}>Przewyższenie: {data.availability?.elevationChart ? `${Math.round(data.activity.insight?.elevationGainM ?? 0)} m` : 'brak danych'} · mocne przyspieszenia: {data.availability?.events ? data.activity.insight?.hardAccelerationCount ?? 0 : 'brak danych'} · hamowania: {data.availability?.events ? data.activity.insight?.hardBrakingCount ?? 0 : 'brak danych'}</Text> : null}{data.previous && data.availability?.comparison && <Text style={[styles.meta, { color: '#4de926' }]}>Ta sama geometria ({Math.round(Number(data.previousSimilarity || 0) * 100)}% podobieństwa): {Number(data.activity.duration || 0) < Number(data.previous.duration || 0) ? `${Math.round(Number(data.previous.duration || 0) - Number(data.activity.duration || 0))} s szybciej` : `${Math.round(Number(data.activity.duration || 0) - Number(data.previous.duration || 0))} s wolniej`}.</Text>}</View>
    <View style={[styles.insight, { backgroundColor: theme.surface, borderColor: theme.border }]}><TelemetryChart label="PRĘDKOŚĆ" available={data.availability?.speedChart === true} values={data.activity.routePoints.map((point) => Number(point.speedKmh)).filter(Number.isFinite)} color="#FFD447" textColor={theme.text} /><TelemetryChart label="WYSOKOŚĆ" available={data.availability?.elevationChart === true} values={data.activity.routePoints.map((point) => Number(point.altitudeM)).filter(Number.isFinite)} color="#22D3EE" textColor={theme.text} /></View>
    <View style={[styles.insight, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.toggle, !canShowSpeedHeatmap && { opacity: 0.45 }]}><Text style={{ color: theme.text, flex: 1 }}>{canShowSpeedHeatmap ? 'Pokaż prędkość w tym udostępnieniu' : 'Prędkość nie została zapisana w tym przejeździe'}</Text><Switch disabled={!canShowSpeedHeatmap} value={canShowSpeedHeatmap && showSpeed} onValueChange={(value) => { setShowSpeed(value); setAsset(null); }} /></View><View style={styles.toggle}><Text style={{ color: theme.text, flex: 1 }}>Pokaż pełny początek i koniec trasy</Text><Switch value={fullRoute} onValueChange={(value) => { setFullRoute(value); setAsset(null); }} /></View></View><View style={styles.actions}><TouchableOpacity style={styles.action} onPress={exportPng}><Text style={styles.actionText}>UDOSTĘPNIJ PNG</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={renderMp4} disabled={rendering || asset?.status === 'queued' || asset?.status === 'processing'}>{rendering ? <ActivityIndicator color="#111" /> : <Text style={styles.actionText}>{asset?.status === 'completed' ? 'MP4 GOTOWY' : asset?.status === 'queued' ? 'W KOLEJCE…' : asset?.status === 'processing' ? 'RENDEROWANIE…' : asset?.status === 'failed' ? 'SPRÓBUJ PONOWNIE' : 'GENERUJ MP4'}</Text>}</TouchableOpacity></View>{renderError ? <Text style={styles.renderError}>{renderError}</Text> : null}{asset?.status === 'completed' && !asset?.publishedPostId && <TouchableOpacity style={styles.publish} onPress={publish} disabled={rendering}><Text style={styles.actionText}>POTWIERDZAM I PUBLIKUJĘ DO VROOMKI</Text></TouchableOpacity>}{asset?.publishedPostId && <View style={styles.actions}><TouchableOpacity style={styles.action} onPress={() => router.push('/Community/vroomki' as any)}><Text style={styles.actionText}>OTWÓRZ VROOMKI</Text></TouchableOpacity><TouchableOpacity style={styles.deleteAction} onPress={deletePublished}><Text style={styles.deleteText}>USUŃ VROOMKĘ</Text></TouchableOpacity></View>}<Text style={[styles.privacy, { color: theme.textDim }]}>Domyślnie ukrywamy prędkość, dokładny start oraz pierwsze i ostatnie 500 m. Zmiany powyżej dotyczą tylko tego jednego materiału.</Text>
  </ScrollView></SafeAreaView>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={{ flex: 1 }}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function TelemetryChart({ label, available, values, color, textColor }: { label: string; available: boolean; values: number[]; color: string; textColor: string }) { const step = Math.max(1, Math.ceil(values.length / 48)); const sample = available ? values.filter((_, index) => index % step === 0).slice(0, 48) : []; const min = sample.length ? Math.min(...sample) : 0; const max = sample.length ? Math.max(...sample) : 1; return <View><Text style={[styles.section, { color: textColor }]}>{label}</Text><View style={styles.chart}>{sample.length ? sample.map((value, index) => <View key={index} style={{ flex: 1, minWidth: 2, height: 5 + ((value - min) / Math.max(1, max - min)) * 65, backgroundColor: color, opacity: 0.45 + index / Math.max(1, sample.length) * 0.5, borderTopLeftRadius: 2, borderTopRightRadius: 2 }} />) : <Text style={{ color: '#888', fontSize: 10 }}>Ten przejazd nie zawiera tej telemetrii</Text>}</View></View>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { height: 56, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontFamily: 'OrbitronBold', fontSize: 14, letterSpacing: 2 }, content: { padding: 16, gap: 14, paddingBottom: 40 }, card: { borderRadius: 20, overflow: 'hidden', paddingBottom: 18 }, map: { height: 360 }, marker: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#fff', borderWidth: 4, borderColor: '#e33835' }, brand: { color: '#FFD447', fontFamily: 'OrbitronBold', fontSize: 13, letterSpacing: 2, margin: 16 }, stats: { flexDirection: 'row', paddingHorizontal: 16 }, statValue: { color: '#fff', fontWeight: '900', fontSize: 14 }, statLabel: { color: '#ffffff70', fontSize: 8, marginTop: 4 }, progressTrack: { height: 4, backgroundColor: '#ffffff18', margin: 16, borderRadius: 2 }, progressFill: { height: 4, backgroundColor: '#FFD447', borderRadius: 2 }, insight: { padding: 16, borderWidth: 1, borderRadius: 16, gap: 12 }, controls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 16 }, rate: { minWidth: 36, minHeight: 30, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, chart: { height: 76, flexDirection: 'row', alignItems: 'flex-end', gap: 2, marginTop: 7 }, toggle: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10 }, section: { fontFamily: 'Orbitron', fontWeight: '900', fontSize: 10 }, meta: { fontSize: 11, lineHeight: 16 }, actions: { flexDirection: 'row', gap: 10 }, action: { flex: 1, minHeight: 48, borderRadius: 12, backgroundColor: '#FFD447', alignItems: 'center', justifyContent: 'center' }, deleteAction: { flex: 1, minHeight: 48, borderRadius: 12, borderWidth: 1, borderColor: '#e33835', alignItems: 'center', justifyContent: 'center' }, deleteText: { color: '#e33835', fontWeight: '900', fontSize: 10 }, publish: { minHeight: 48, borderRadius: 12, backgroundColor: '#4de926', alignItems: 'center', justifyContent: 'center' }, actionText: { color: '#111', fontWeight: '900', fontSize: 10 }, renderError: { color: '#e33835', fontSize: 11, lineHeight: 16, textAlign: 'center' }, privacy: { fontSize: 10, lineHeight: 15, textAlign: 'center' }, error: { margin: 30, textAlign: 'center' } });
